name: Compilador Indestructible Mesa 25

on:
  push:
    branches: [ "wrapper-25" ]
  pull_request:
    branches: [ "wrapper-25" ]
  workflow_dispatch:

jobs:
  build-driver:
    runs-on: ubuntu-24.04

    steps:
      - name: 🔍 Obtener código fuente de gamenative-wrapper
        uses: actions/checkout@v4
        with:
          ref: 'wrapper-25'

      - name: ⚙️ Instalar dependencias del sistema operativo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip meson ninja-build patchelf zstd unzip curl git

      - name: 🤖 Configurar Android NDK r28
        run: |
          mkdir -p /tmp/ndk
          cd /tmp/ndk
          curl -L "https://google.com" -o ndk.zip
          unzip -q ndk.zip
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo mv android-ndk-r28 /usr/local/lib/android/sdk/ndk/28.2.13676358

      - name: 🚀 Ejecutar Enlazador Híbrido Monolítico desde build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: 📦 Subir Driver Compilado como Artefacto de GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Mesa25-Panfrost-Wrapper
          path: wrapper.tzst
