name: Build Funnymdzz PanVK for Bannerlator

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite lanzar la compilación manualmente desde la web

jobs:
  build-panvk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prune Docker Cache Aggressively
      run: |
        docker builder prune -a -f
        docker system prune -a -f

    - name: Build PanVK Package via Docker
      run: |
        docker build --no-cache -f Dockerfile.build --target final -t bannerlator-panvk-builder .

    - name: Extract Bannerlator Package
      run: |
        docker create --name container-extract bannerlator-panvk-builder
        docker cp container-extract:/dist/panvk-mali-bannerlator.tar.xz ./panvk-mali-bannerlator.tar.xz
        docker rm container-extract

    - name: Upload Package to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: panvk-mali-bannerlator-driver
        path: panvk-mali-bannerlator.tar.xz
